# Generated by Django 3.2.2 on 2021-05-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_author', models.CharField(max_length=100)),
                ('quote_body', models.TextField()),
                ('context', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
